import { Meta } from "@storybook/react/types-6-0";
declare const _default: Meta<import("@storybook/react").Args>;
export default _default;
export declare const Townhall: any;
export declare const SkillWalletNav: any;
export declare const Settings: any;
export declare const Notifications: any;
export declare const Logoff: any;
export declare const FooterShare: any;
export declare const FooterMembers: any;
