import { Meta } from "@storybook/react/types-6-0";
declare const _default: Meta<import("@storybook/react").Args>;
export default _default;
export declare const LayerBlur: any;
export declare const Shape1: any;
export declare const Shape2: any;
export declare const Shape3: any;
export declare const Shape4: any;
export declare const Shape5: any;
export declare const Shape6: any;
export declare const Shape7: any;
