import { Meta } from "@storybook/react/types-6-0";
declare const _default: Meta<import("@storybook/react").Args>;
export default _default;
export declare const JoinSel: any;
export declare const JoinUnsel: any;
export declare const CreateUnsel: any;
export declare const DitoCredits: any;
export declare const GameTheory: any;
export declare const NetworkDesign: any;
export declare const Tokenomics: any;
